import Head from 'next/head'
import Hero from '../components/general/Hero'

export default function About() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height='h-[45vh]' url="https://images.unsplash.com/photo-1536505676517-18e3f57d24b3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"/>
    </div>
  )
}