import Head from 'next/head'
import Hero from '../components/general/Hero'
import ContactFormat from '../components/site/contact/ContactFormat'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height='h-[55vh]' url="https://images.unsplash.com/photo-1563305549-4ee002e6c3fd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2064&q=80"/>
      <ContactFormat />
    </div>
  )
}