import Head from 'next/head'
import Hero from '../components/general/Hero'
import ContactFormat from '../components/site/contact/ContactFormat'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height='h-[45vh]' />
      <ContactFormat />
    </div>
  )
}