import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello Maurice</div>
    </div>
  )
}