import Head from 'next/head'
import Hero from '../components/general/Hero'
import IntroPanel from '../components/site/home/IntroPanel'
import ServiceList from '../components/site/home/ServiceList'
import SignUp from '../components/forms/SignUp'
import Testimonials from '../components/site/home/Testimonials'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height='h-screen' />
      <IntroPanel />
      <ServiceList />
      <Testimonials />
      <SignUp />
    </div>
  )
}
