import Head from 'next/head'
import Hero from '../components/general/Hero'

export default function Prices() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - Prices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height='h-72 sm:h-[55vh]' url="https://images.unsplash.com/photo-1559317245-d24c4c7f252b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"/>
    </div>
  )
}
