import Head from 'next/head'
import Hero from '../components/general/Hero'

export default function Prices() {
  return (
    <div>
      <Head>
        <title>Pet Concierge SA - Prices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height='h-[60vh]' />
    </div>
  )
}
